### ISSUE TITLE
Put non-windows release files into archives

### ISSUE THREAD

**Issue by ethteck** [ethteck/bdiff#34]
so they have execute perms

when downloading a plain executable from the internet, it doesn't start with +x automatically. however, when extracted from an archive, it keeps the permissions it had in the archive. we can make people's lives easier by putting the releases into archives with +x already set, so users can just extract and go

**Comment by MGlolenstine** [comment]
Would something like this work?
```
ls | grep -v "\.exe$" | xargs -I@ sh -c "zip -r @.zip @ && rm @"
```
This lists all files that don't end with `.exe`, which should be all files but Windows', throws them into a `<filename>.zip` archive and removes the original file.

This would be added into a new "step" [here](https://github.com/ethteck/bdiff/blob/main/.github/workflows/rust.yml#L98).

We could also add the executable flag before archiving it with something like this:
```
ls | grep -v "\.exe$" | xargs -I@ sh -c "chmod +x @ && zip -r @.zip @ && rm @"
```


## Before running the command
```
bdiff-linux-x86_64
bdiff-macos-arm64
bdiff-macos-x86_64
bdiff-windows-x86_64.exe
```

## After running the command
```
bdiff-linux-x86_64.zip
bdiff-macos-arm64.zip
bdiff-macos-x86_64.zip
bdiff-windows-x86_64.exe
```

**Comment by ethteck** [comment]
sounds great! this would work. I was thinking there might be some github action that already does this, but your solution is just as good if not better

**Comment by MGlolenstine** [comment]
I'd love to implement this, but I'm unsure of how to test the actions globally without having to push into releases.

Is there a guide on how to do that or is it just trial and error?

**Comment by ethteck** [comment]
we should have it so builds produce artifacts even if they're not released. that way any push will still build the files and stuff

**Comment by sergeevabc** [comment]
Windows 7 x64 user here.
Launching `bdiff-windows-x86_64.exe` does nothing on my end.

**Comment by ethteck** [comment]
Hi @sergeevabc! Where did you get that file from? Also, the Windows release has nothing to do with this issue. That being said, I know the latest release works on Windows 11. I unfortunately have no Windows 7 environment on which to test the release. But if it is silently doing nothing and not even popping open a window, I think that's probably an upstream issue with eframe or winit

**Comment by sergeevabc** [comment]
@ethteck, I have downloaded bdiff 0.8.5 from Releases section here today. Quite a surprise that the program doesn't work. After all, other programs with diff-abilities such as [Xdelta](https://github.com/jmacd/xdelta-gpl), [Hdiffz](https://github.com/sisong/HDiffPatch/), [JojoDiff,](https://jojodiff.sourceforge.net/) and [Zstandard](https://github.com/facebook/zstd/wiki/Zstandard-as-a-patching-engine) are still working properly.

**Comment by ethteck** [comment]
The fact that a program does diffing has no bearing on whether it's compatible with your operating system. I don't think any of those even are written in the same language as bdiff.

If you're interested in getting it to work, feel free to write a new issue, and I can work with you there to troubleshoot and diagnose why it might not be working.
