### ISSUE TITLE
[Linux] Release 0.8.5 requires `libpython3.10.so.1.0`

### ISSUE THREAD

**Issue by Dragorn421** [ethteck/bdiff#57]
Downloading release build at https://github.com/ethteck/bdiff/releases/download/0.8.5/bdiff-linux-x86_64

Running on Linux (specifically, Kubuntu 24.04) fails with the following message:

`/home/dragorn421/Downloads/bdiff-linux-x86_64: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

**Comment by ethteck** [comment]
@Dragorn421 could you test the latest release on Linux? It's instantly exiting on WSL for me, but I think that's just my WSL not playing well with it for whatever reason

**Comment by Dragorn421** [comment]
It exits immediately for me too (no window even appears). No message.
It's not crashing, according to running in gdb:
```
(gdb) run
Starting program: /home/dragorn421/Downloads/bdiff-linux-x86_64(2) 
[Inferior 1 (process 109361) exited normally]
```

**Comment by ethteck** [comment]
Fixed in latest commit by switching to the gnu target from musl
